In [ ]:

import pandas as pd

In [ ]:
# Load the dataset
df=pd.read_csv(r'C:\Users\Admin\Desktop\project\customer_shopping_behavior.csv')

In [4]:
#to get top 5 rows of the data
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
# to get the summary of the data
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
#to get null values in the data
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
#to replace null values(review rating ) using median
#review rating affects each category differently so we will replace null values with median of each category

df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum().sum() # to get total null values in the data

np.int64(0)

In [9]:
#rename column names
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [ ]:
#to get column names
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [11]:
#create colum age_group to categorize customers into age groups
labels=['young_adult','adult','middle-aged','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)  #young adult: 18-30, adult: 31-45, middle-aged: 46-60, senior: 61 and above

In [12]:
#want to see how q is categorized
# print q values
#young adult: 18-30, adult: 31-45, middle-aged: 46-60, senior: 61 and above   
print(pd.qcut(df['age'],q=4).unique())

[(44.0, 57.0], (17.999, 31.0], (57.0, 70.0], (31.0, 44.0]]
Categories (4, interval[float64, right]): [(17.999, 31.0] < (31.0, 44.0] < (44.0, 57.0] < (57.0, 70.0]]

In [ ]:
#to see age and age group columns
df[['age','age_group']].head(10)

   age    age_group
0   55  middle-aged
1   19  young_adult
2   50  middle-aged
3   21  young_adult
4   45  middle-aged
5   46  middle-aged
6   63       senior
7   27  young_adult
8   26  young_adult
9   57  middle-aged

In [ ]:
#to categorize customers based on frequency of purchases
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [15]:
#create purchse_frequency_day column to categorize customers into purchase frequency groups
frequency_mapping={
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Annually': 365,
    'Every 3 Months': 90,
    'Bi-Weekly': 14
}

df['purchase_frequency_day']=df['frequency_of_purchases'].map(frequency_mapping)

In [ ]:
#to see purchase frequency day and frequency of purchases columns
df[['purchase_frequency_day','frequency_of_purchases']].head(10)

   purchase_frequency_day frequency_of_purchases
0                      14            Fortnightly
1                      14            Fortnightly
2                       7                 Weekly
3                       7                 Weekly
4                     365               Annually
5                       7                 Weekly
6                      90              Quarterly
7                       7                 Weekly
8                     365               Annually
9                      90              Quarterly

In [ ]:
#to drop duplicates in purchase frequency day and frequency of purchases columns and see unique values
df[['purchase_frequency_day','frequency_of_purchases']].drop_duplicates().head(10)

    purchase_frequency_day frequency_of_purchases
0                       14            Fortnightly
2                        7                 Weekly
4                      365               Annually
6                       90              Quarterly
10                      14              Bi-Weekly
15                      30                Monthly
20                      90         Every 3 Months

In [ ]:
#to see discount applied and promo code used columns
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [19]:

(df['discount_applied'] == df['promo_code_used']).all() #check if discount_applied and promo_code_used are the same

np.True_

In [20]:

# Dropping promo code used column : since discount_applied and promo_code_used are the same we can drop one of them to avoid redundancy

df = df.drop('promo_code_used', axis=1)

In [21]:

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_day'],
      dtype='str')

In [ ]:
#to check number of duplicates in the data
df.duplicated().sum()

np.int64(0)

In [ ]:
#to remove whitespace from column names
df.columns = df.columns.str.strip()

In [24]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young_adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle-aged,365

sql connection

In [ ]:

!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "root1"
host = "127.0.0.1"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [ ]:
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [ ]:
# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

3900

In [ ]:
# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young_adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle-aged,365